USE mysql;

DROP DATABASE IF EXISTS TrendingFlicks;

CREATE DATABASE IF NOT EXISTS TrendingFlicks CHARACTER SET utf8 COLLATE utf8_general_ci;

USE TrendingFlicks;

CREATE TABLE likeFlicks (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	userId VARCHAR(512) NOT NULL,
	imdbId VARCHAR(512) NOT NULL,
	CONSTRAINT uLike UNIQUE (userId,imdbId)
);

CREATE TABLE seenFlicks (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	userId VARCHAR(512) NOT NULL,
	imdbId VARCHAR(512) NOT NULL,
	CONSTRAINT uLike UNIQUE (userId,imdbId)
);

CREATE TABLE topFlicks (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	flickType VARCHAR(128),
	imdbId VARCHAR(512) NOT NULL,
	rating VARCHAR(512)
);


-- USE TrendingFlicks;
-- SELECT * FROM seenFlicks;

-- ALTER TABLE `Media` MODIFY COLUMN `Title` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL ;
-- ALTER TABLE `Media` MODIFY COLUMN `Source` VARCHAR(5120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL ;
-- ALTER TABLE `Media` MODIFY COLUMN `Owner` VARCHAR(5120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL ;